### ISSUE TITLE
No text on red/pink background

### ISSUE THREAD

**Issue by elkrien** [catppuccin/github#21]
I think the screen will explain everything:
![image](https://user-images.githubusercontent.com/78103450/175091663-224fd80d-91ef-45b1-b449-c5b313f87126.png)
Text is visible after hoovering on switch.

**Comment by andreasgrafen** [comment]
Hmm, that's interesting. Do you have any other Styles active for Github that could cause this?

This is how these settings look for me:
<img width="814" alt="Screen Shot 2022-06-22 at 19 01 21" src="https://user-images.githubusercontent.com/35840154/175095734-64f98453-00c1-4f27-803e-320ba2054784.png">

**Comment by elkrien** [comment]
No. I use only this one. I will try to remove it and install again and check if this repeats. Will let You know.

**Comment by andreasgrafen** [comment]
Well.. caching can be a pain in the back. o:
