### ISSUE TITLE
GitHub Actions UI looking off with Latte theme

### ISSUE THREAD

**Issue by jeffijoe** [catppuccin/github#28]
A continuation of #27 — opening a new issue as requested.

Screenshot:

![image](https://user-images.githubusercontent.com/2505474/190691249-d1b61f9f-70a0-4d27-9dc4-8e040b33562a.png)

**Comment by andreasgrafen** [comment]
<img width="723" alt="GitHub Actions Flowchart" src="https://user-images.githubusercontent.com/35840154/226169514-2917255f-ce1b-4193-951b-163a92553fef.png">
<img width="732" alt="GitHub Actions Job Details" src="https://user-images.githubusercontent.com/35840154/226169565-6dfa7f1a-39bc-40a2-aca9-75bf0b40ee44.png">
