### ISSUE TITLE
Github Actions Marketplace missing large portion of styles

### ISSUE THREAD

**Issue by djames-bloom** [catppuccin/github#30]
## Problem
(rel: #28) 

The Actions marketplace UI remains mostly unstyled, with only a small subsection of the UI being restyled. Due to text not being styled on the page for specific actions, the content is close to illegible on the darker variants.

### Marketplace index - [Link](https://github.com/marketplace)
![image](https://user-images.githubusercontent.com/89976687/190837763-a3d54ee3-822e-42b3-b3be-e6a2bf0f02fc.png)

### Actions index - [Link](https://github.com/marketplace?type=actions)
![image](https://user-images.githubusercontent.com/89976687/190837776-da59280b-17ab-4f54-b566-60f80db74dd7.png)

### Action detail page - [Link](https://github.com/marketplace/actions/setup-jira)
![image](https://user-images.githubusercontent.com/89976687/190837790-bbe08b9b-7d08-41ae-9a7d-afcd2b8cd8d6.png)

**Comment by rbutera** [comment]
@djames-bloom the marketplace is unreadable with this theme, so I made a PR to disable the theme on the marketplace, and enable it on all other github urls.

You can [copy the necessary changes here while we wait for the PR to be merged](https://github.com/catppuccin/github/pull/32): https://github.com/catppuccin/github/pull/32
