### ISSUE TITLE
Disabled buttons illegible on Frappe

### ISSUE THREAD

**Issue by djames-bloom** [catppuccin/github#31]
## Problem
When working in an organisation that does not allow forking, the fork button is disabled. When this is the case, the text, and icon, on the button are illegible and users must rely on the on-hover tooltip to know what the button is for

## Example
![image](https://user-images.githubusercontent.com/89976687/190880311-bcc4ae38-ea3c-45e2-89ce-637f19818122.png)

**Comment by andreasgrafen** [comment]
Sadly Github still uses the same background colour for the buttons, so the only way to differentiate disabled buttons is the text colour. I've used the accent colour to fix this, as making the text use dark colours doesn't work in favour of legibility either. 

![rosewater accent](https://user-images.githubusercontent.com/35840154/195716894-5a6b3a7e-886f-4701-8214-ede169508d97.png)
![blue accent](https://user-images.githubusercontent.com/35840154/195716945-ad47a3a6-f918-4246-ae03-17b9efd590e8.png)
