### ISSUE TITLE
comment showing as a weird color when browsing code

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/github#35]
![SCR-20221013-m6h](https://user-images.githubusercontent.com/72631767/195709404-b14aa961-27be-4f44-a9c1-c974b46a4498.png)
![SCR-20221013-m6x](https://user-images.githubusercontent.com/72631767/195709410-d9e0791b-7c5e-41db-84d6-e6fa8f7c8738.png)

**Comment by andreasgrafen** [comment]
Just for tracking: The cause for this was one of the still existing placeholders for prettylights syntax as we still don't know what some of them do. Thus they're placed as hotpink in order to stand out.
In this case it was the invalid syntax highlighting as json files don't support comments.
