### ISSUE TITLE
how can i use this theme in other browsers?

### ISSUE THREAD

**Issue by command-z-z** [catppuccin/github#42]
now I use qutebrowsers, can I use catppuccin in this browser?

**Comment by nekowinston** [comment]
An example of "other browsers" would be helpful.

**Comment by command-z-z** [comment]
> An example of "other browsers" would be helpful.

qutebrowser

**Comment by nekowinston** [comment]
Using stylus to compile your settings to plain CSS, then using`content.user_stylesheets` in the qutebrowser config.

Point 21 on https://qutebrowser.org/doc/faq.html.

It's a bit out of scope for all of our userstyles, since they're explicitly made for Stylus/Stylish.

**Comment by command-z-z** [comment]
> Using stylus to compile your settings to plain CSS, then using`content.user_stylesheets` in the qutebrowser config.
> 
> Point 21 on https://qutebrowser.org/doc/faq.html.
> 
> It's a bit out of scope for all of our userstyles, since they're explicitly made for Stylus/Stylish.

oh, I will have a try. Ty:)

**Comment by nekowinston** [comment]
Glad I could help somewhat, custom userstyles are sadly a bit of a pain in Qutebrowser.

We can't really officially support them at the moment, so I'll close the issue.
