### ISSUE TITLE
Repository visibility scope buttons illegible

### ISSUE THREAD

**Issue by djames-bloom** [catppuccin/github#46]
### Problem
The action buttons and modal confirm button in the "danger zone" section, when changing the visibility of a repo (e.g. from internal to private) are illegible until hovered over

### Danger zone section 
**Standard button state**
![Screenshot 2023-03-06 at 22 53 12](https://user-images.githubusercontent.com/89976687/223275160-f99c74d1-f8fd-4a52-9bc8-50d329b88fa6.png)

**Hover state**
![Screenshot 2023-03-06 at 22 56 04](https://user-images.githubusercontent.com/89976687/223275349-068c542e-7352-4799-9766-adbd2cff704c.png)

### Scope modal
**Standard button state**
![Screenshot 2023-03-06 at 22 53 58](https://user-images.githubusercontent.com/89976687/223275239-7bcd07ff-6733-4bb1-a93c-3e23e7f3991c.png)

**Hover state**
![Screenshot 2023-03-06 at 22 57 36](https://user-images.githubusercontent.com/89976687/223275547-957e8e13-4380-468f-8896-bb6be3b85434.png)

**Comment by andreasgrafen** [comment]
Cool Story! Apparently `.btn-danger` wasn't enough, so now there also is `.Button--danger`.. 🤔
Anyhow; a fix is on the way.
