### ISSUE TITLE
After the (probably) github update text is not visible anymore

### ISSUE THREAD

**Issue by mokrinsky** [catppuccin/github#49]
I assume today github released some css update and theme doesn't work properly anymore. Screenshot is attached as an example.

I use latest version of userstyle for Stylus with autoupdate turned on.

![image](https://user-images.githubusercontent.com/463907/228366371-0b8229a5-2e78-4980-8c46-d54937c34cac.png)

**Comment by skbolton** [comment]
https://github.blog/changelog/2023-03-28-light-and-dark-theme-color-contrast-improvements/

**Comment by ghostx31** [comment]
Fixed with 92dc5f9
