### ISSUE TITLE
Inconsistencies/errors

### ISSUE THREAD

**Issue by mainrs** [catppuccin/github#5]
Some screenshots of inconsistencies/errors that I stumbled across:

This is the GitHub workflow "header" when contributing the first time to a repository that has workflows enabled. The icons are quite dark. Here is the PR: https://github.com/NixOS/nixpkgs/pull/157047
![Screenshot_20220127_213658](https://user-images.githubusercontent.com/5113257/151439959-341d08f4-228f-49f1-b7ad-190352ec1244.png)

The lower border corners of notifications are not connected. 
![Screenshot_20220127_213820](https://user-images.githubusercontent.com/5113257/151440033-d4ef9d79-7cd2-4b39-89ef-bbda3406f3a8.png)

**Comment by andreasgrafen** [comment]
Thanks a lot for reaching out with your feedback! c:
The first one was easy to fix and the changes are already pushed and available as of right now.

The second thing you've mentiones is a little more tricky. For some reason the border consist of two parts – the side borders being part of the surrounding container, while the bottom border is part of the list footer. There probably is an easy solution for this, but I might just be too tired to come up with it on the spot? I'll get back to this once I have cought some sleep..

**Comment by mainrs** [comment]
The mention is really hard to read:
![image](https://user-images.githubusercontent.com/5113257/151590909-3554ebb3-864f-460f-a4bc-2f22c5c150d2.png)

Either change the text color to something dark for more contrast. Or maybe another color, like red?

**Comment by mainrs** [comment]
> The first one was easy to fix and the changes are already pushed and available as of right now.

I've updated the CSS (using Refined GitHub) but it still shows the same for me:
![image](https://user-images.githubusercontent.com/5113257/151591434-463e1042-f74c-41e1-b351-a0c9f3def59d.png)

Deleted cache before checking.

**Comment by andreasgrafen** [comment]
Okay, that's odd. I've tried a different apporach to fix the Icons; mind giving it another shot real quick please? c:
The mentions should also be more legible now. @mainrs @andreasgrafen

**Comment by mainrs** [comment]
Looks like it has something to do with my refined github installation. firefox doesn't save the updated css, so i always inject the old one.

**Comment by mainrs** [comment]
I think a better approach might to to open one issue per error found. It's easier to keep track that way :)

**Comment by andreasgrafen** [comment]
> Looks like it has something to do with my refined github installation. firefox doesn't save the updated css, so i always inject the old one.

okay.. that's just annoying. if you use it **only** for the CSS you might as well want to try stylus? otherwise … i don't know how to combat that. o:
