### ISSUE TITLE
Text contrast is lacking in dark variants

### ISSUE THREAD

**Issue by andreiborisov** [catppuccin/github#50]
<img width="763" alt="CleanShot 2023-03-29 at 20 02 35@2x" src="https://user-images.githubusercontent.com/13354491/228599277-dc5da14c-92c6-4b42-b59a-6ee1ae668a41.png">

Contrast is lacking throughout the whole GitHub.

**Comment by ghostx31** [comment]
FIxed with 92dc5f9

**Comment by andreiborisov** [comment]
Wow, that was insanely fast, thank you!
