### ISSUE TITLE
Jupyter notebook theming 

### ISSUE THREAD

**Issue by Siris01** [catppuccin/github#53]
Jupyter notebooks aren't themed. 
I have implemented most of the theme, but one thing to note here is that GitHub uses iframes to render .ipynb files, so the target url for the style file would be different.
Should I PR a separate file to this repo? or is a new repo needed?

**Comment by andreasgrafen** [comment]
Awesome!

There probably isn't a way of making sure these iframes are scoped to just be applied in GitHub, right? Leaking styles are dangerous, but depending on a second userstyle also sucks.
I'd prob. just run with the risk of it potentially leaking, and fixing it from there. So imo you can just PR your changes to this Repo. c:

**Comment by Siris01** [comment]
Alright, i'll PR it in a while
