### ISSUE TITLE
New notifications do not have a style applied

### ISSUE THREAD

**Issue by mainrs** [catppuccin/github#6]
This notification is new/unread:

![image](https://user-images.githubusercontent.com/5113257/151665327-00c1e3e9-39f7-413f-91d2-672952195e52.png)

**Comment by andreasgrafen** [comment]
<img width="508" alt="Screen Shot 2022-01-29 at 19 14 52" src="https://user-images.githubusercontent.com/35840154/151672574-832137c7-b665-4c9d-9c57-61e1739050a7.png">

I can't reproduce that on my end. Is there some experimental theme update Github is rolling out only partially? I wasn't able to find something on the settings. o:

**Comment by mainrs** [comment]
I am part of the `Colorblind` and `Light Contrast` previews. I have the normal  light default theme enabled in my preferences though.

**Comment by andreasgrafen** [comment]
Okay.. I've just switched to `Light Colourblind` in my settings, but the notifications still looks properly. Tho, your notifications look slightly different – more compact. I can't find a setting for that.

**Comment by mainrs** [comment]
@andreasgrafen You might need to change the grouping of them: 
![image](https://user-images.githubusercontent.com/5113257/151676033-7b7b15ba-c4f5-499f-8812-14d6c5a2e299.png)

**Comment by andreasgrafen** [comment]
ooh, I see! Why-ever that changes the styling, but you're right. Thanks! c:
I've updated the background var, so it should be nice and dark with the latest version.

**Comment by mainrs** [comment]
Thank you!
