### ISSUE TITLE
Icons inside of issue timeline are wrongly colored

### ISSUE THREAD

**Issue by mainrs** [catppuccin/github#7]
For timeline items inside of issues the icons are not colored correctly:
![image](https://user-images.githubusercontent.com/5113257/151715395-5389da79-0c3a-4b8c-bc48-caaff3ae054b.png)
https://github.com/mainrs/nixos-config/issues/8

**Comment by andreasgrafen** [comment]
I'm gonna use the Light Theme from now on. I would have never spotted that with the Dark Theme in the background. Thank you so much for all the issue tracking. ^^—^
