### ISSUE TITLE
Using comments inside of a `json` codeblock creates hard to read text

### ISSUE THREAD

**Issue by mainrs** [catppuccin/github#8]
https://github.com/dhall-lang/dhall-haskell/issues/2374#issue-1119871430

![image](https://user-images.githubusercontent.com/5113257/151864198-0f934b95-454c-45b4-9d66-95b347d50c00.png)

The code block looks like this:

<pre>
```json
// .vscode/settings.json
{
    "vscode-dhall-lsp-server.server.contextFile": "${workspaceRoot}/ApiContext.dhall"
}
```
</pre>

**Comment by andreasgrafen** [comment]
Fixed. This should also fix some of the other issues the prettylights highlighting still had. c:
